modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="antique_pickaxe"
version="0.2"
displayName="antique_pickaxe"
credits="un mod avec une pioche !"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="cedrou"
description='''
antique_pickaxe_mod
'''

[[dependencies.antique_pickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




