modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="antique_pickaxe"
version="0.9.1"
displayName="antique_pickaxe"
credits="un mod avec une pioche !"
displayURL="https://www.curseforge.com/minecraft/mc-mods/antique-pickaxe"
logoFile="logo.png"
authors="cedrou"
description='''
antique pickaxe mod (evolving pickaxe)
'''

[[dependencies.antique_pickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




