modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="antique_pickaxe"
version="0.1"
displayName="antique_pickaxe"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="cedrou"
description='''
antique_pickaxe_mod
'''

[[dependencies.antique_pickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




