modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="antique_pickaxe"
version="1.0.1"
displayName="antique_pickaxe"
displayURL="https://www.curseforge.com/minecraft/mc-mods/antique-pickaxe"
logoFile="logo.png"
credits="un mod avec une pioche !"
authors="cedr0u"
description="antique pickaxe mod (evolving pickaxe)"

[[dependencies.antique_pickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




